create or replace view `wh_dimension.DIM_CUSTOMER_DEMOGRAPHICS_VW` as
select
CD_DEMO_SK,
CD_GENDER_TH,
CD_EDUCATION_STATUS,
CD_MARITAL_STATUS,
CD_CREDIT_RATING
from wh_conformed.CUSTOMER_DEMOGRAPHICS_VW
